use-conda: True 
cluster: "sbatch --parsable -p engreitz -C GPU_MEM:16GB -G 1 --ntasks 1 --time {resources.runtime_hr}:00:00"
cluster-cancel: scancel
default-resources: "runtime_hr=24"
jobs: 100
rerun-triggers: mtime
